__all__=[
	"CaptureScreenshot",
	"MaximizeBrowserWindow",
	"SelectWindow",
	"SetSeleniumSpeed",
	"SetSeleniumTimeout",
	"WaitUntilPageContains",
	"WaitUntilPageContainsElement",
	"WaitUntilPageLoaded"
]