#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Nov 29 00:14:36 2009

import wx

# begin wxGlade: extracode
# end wxGlade


class SimulationDialog(wxFrame, wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SimulationDialog.__init__
        kwds["style"] = wx.ICONIZE|wx.MINIMIZE|wx.CLOSE_BOX
        wxFrame.__init__(self, *args, **kwds)
        wxPanel.__init__(self)
        self.timeLabel = wx.StaticText(self, -1, _("Final time"), style=wx.ALIGN_CENTRE)
        self.timeControl = wx.TextCtrl(self, -1, _("10"))
        self.runButton = wx.ToggleButton(self, -1, _("Run"))
        self.stopButton = wx.Button(self, -1, _("Stop"))
        self.suspendButton = wx.ToggleButton(self, -1, _("Suspend"))
        self.logButton = wx.Button(self, -1, _("Log"))
        self.gauge_1 = wx.Gauge(self, -1, 10)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SimulationDialog.__set_properties
        self.SetTitle(_("Simulation"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/home/capocchi/Documents/Projets/ENR/Prog/DEVSimPy/Python2_6/Gui/icons2/20x20/simulation.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((260, 190))
        self.timeLabel.SetFocus()
        self.timeControl.SetMinSize((100, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SimulationDialog.__do_layout
        boxSize1 = wx.BoxSizer(wx.VERTICAL)
        boxSizer2 = wx.BoxSizer(wx.VERTICAL)
        gridSizer1 = wx.GridSizer(3, 2, 0, 0)
        gridSizer1.Add(self.timeLabel, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        gridSizer1.Add(self.timeControl, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        gridSizer1.Add(self.runButton, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        gridSizer1.Add(self.stopButton, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        gridSizer1.Add(self.suspendButton, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        gridSizer1.Add(self.logButton, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        boxSize1.Add(gridSizer1, 1, wx.EXPAND, 0)
        boxSizer2.Add(self.gauge_1, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        boxSize1.Add(boxSizer2, 1, wx.EXPAND, 0)
        self.SetSizer(boxSize1)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class SimulationDialog


if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Simulation = SimulationDialog(None, -1, "")
    app.SetTopWindow(Simulation)
    Simulation.Show()
    app.MainLoop()
