#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Mar 13 16:28:17 2013

import wx
import os

# begin wxGlade: extracode
# end wxGlade

class SimManagerGUI(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: SimManagerGUI.__init__
		wx.Frame.__init__(self, *args, **kwds)
		self.nb = wx.Notebook(self, -1, style=wx.NB_LEFT)
		self.models_manager = wx.Panel(self.nb, -1)
		self.window_1 = wx.SplitterWindow(self.models_manager, -1, style=wx.SP_3D | wx.SP_BORDER)
		self.window_1_pane_1 = wx.Panel(self.window_1, -1)
		self.model_label = wx.StaticText(self.window_1_pane_1, -1, _("Models"))
		self.window_1_pane_2 = wx.Panel(self.window_1, -1)
		self.method_label = wx.StaticText(self.window_1_pane_2, -1, _("Methods"))
		self.notebook_1_pane_2 = wx.Panel(self.nb, -1)
		self.CCS_list = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
		self.delBtn = wx.Button(self.notebook_1_pane_2, wx.ID_DELETE, "")
		self.addBtn = wx.Button(self.notebook_1_pane_2, wx.ID_ADD, "")

		self.__set_properties()
		self.__do_layout()

	# end wxGlade

	def __set_properties(self):
		# begin wxGlade: SimManagerGUI.__set_properties
		self.SetTitle(_("CCS Manager"))
		_icon = wx.EmptyIcon()
		_icon.CopyFromBitmap(wx.Bitmap(os.path.join(ICON_PATH, 'Windows', 'IconDEVSimPy_XP.ico'), wx.BITMAP_TYPE_ANY))
		self.SetIcon(_icon)
		self.SetSize((557, 333))
		self.model_label.SetToolTipString(_("Concurrent model list"))
		self.method_label.SetToolTipString(_("Choose prefix methods for concTransition method"))
		self.CCS_list.SetToolTipString(_("List of current CCS"))
		self.delBtn.SetToolTipString(_("Delete the selected cucurrent simulation"))
		self.addBtn.SetToolTipString(_("Add new concurrent simulation"))
		self.addBtn.SetDefault()

	# end wxGlade

	def __do_layout(self):
		# begin wxGlade: SimManagerGUI.__do_layout
		sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_5 = wx.BoxSizer(wx.VERTICAL)
		sizer_btn = wx.BoxSizer(wx.HORIZONTAL)
		sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_4 = wx.BoxSizer(wx.VERTICAL)
		self.sizer_3 = wx.BoxSizer(wx.VERTICAL)
		self.sizer_3.Add(self.model_label, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.window_1_pane_1.SetSizer(self.sizer_3)
		self.sizer_4.Add(self.method_label, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.window_1_pane_2.SetSizer(self.sizer_4)
		self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
		sizer_2.Add(self.window_1, 1, wx.EXPAND, 0)
		self.models_manager.SetSizer(sizer_2)
		sizer_5.Add(self.CCS_list, 2, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_btn.Add(self.delBtn, 1, wx.BOTTOM, 0)
		sizer_btn.Add(self.addBtn, 1, wx.BOTTOM, 0)
		sizer_5.Add(sizer_btn, 0, wx.BOTTOM | wx.EXPAND, 0)
		self.notebook_1_pane_2.SetSizer(sizer_5)
		self.nb.AddPage(self.models_manager, _("Models"))
		self.nb.AddPage(self.notebook_1_pane_2, _("Simulations"))
		sizer_1.Add(self.nb, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_1)
		self.Layout()
		self.Centre()

	# end wxGlade

# end of class SimManagerGUI
if __name__ == "__main__":
	app = wx.PySimpleApp()
	wx.InitAllImageHandlers()
	frame = SimManagerGUI(None, -1, "")
	app.SetTopWindow(frame)
	frame.Show()
	app.MainLoop()
