name: Test Installing DEVSimPy on Windows (latest), using conda

on:
    push:
      branches:
        - master

jobs:
  build-windows:
    runs-on: windows-latest  # Windows-only runner
    strategy:
      matrix:
        python-version: ['3.10']
    # defaults:
    #   run:
    #     shell: pwsh  # PowerShell pour Windows
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python with Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        conda-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        python-version: ${{ matrix.python-version }}

    - name: Install conda dependencies
      run: |
        conda install -y -c conda-forge python=${{ matrix.python-version }} numpy=>1.22 matplotlib=>3.6 wxpython>=4.2.2 pip
        conda info -a
        conda list

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
            psutil \
            pyYAML \
            PyPubSub \
            ruamel.yaml \
            matplotlib \
            openai \
            ollama
    
    - name: Test DEVSimPy on Windows
      run: |
        python devsimpy.py examples/model0/model0.dsp 10 start quit
