### Test Installing DEVSimPy on Windows (latest), using conda

### To use from DEVSimPy local repo: 
###   1. lauch Docker
###   2. open a powershell terminal
###   3. execute: act -j build-windows -P windows-latest=ghcr.io/catthehacker/ubuntu:act-latest
###   4. if act is not installed, execute: winget install nektos.act
###   5. restart the terminal
  
name: Windows build

on:
    push:
      branches:
        - master

jobs:
  build-windows:
    runs-on: windows-latest  # Windows-only runner
    strategy:
      max-parallel: 4
      fail-fast: true # Stop all jobs if one fails
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4

    - name: Remove existing Miniconda directory if it exists
      run: |
        $miniconda_path = "C:/Users/capocchi_l/miniconda3"
        if (Test-Path $miniconda_path) {
          Remove-Item -Recurse -Force $miniconda_path
        }
      shell: powershell
      
    - name: Set up Python with Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: latest
        conda-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        python-version: ${{ matrix.python-version }}

    # - name: Install VcXsrv
    #   run: |
    #     Invoke-WebRequest -Uri "https://sourceforge.net/projects/vcxsrv/files/latest/download" -OutFile "$env:TEMP\vcxsrv_installer.exe"
    #     Start-Process -Wait -FilePath "$env:TEMP\vcxsrv_installer.exe" -ArgumentList "/silent", "/verysilent", "/norestart"
    #   shell: powershell

    # - name: Start VcXsrv
    #   run: |
    #     Start-Process -NoNewWindow -FilePath "C:\Program Files\VcXsrv\vcxsrv.exe" -ArgumentList ":0 -multiwindow -clipboard -wgl"
    #     echo "DISPLAY=127.0.0.1:0.0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    #   shell: powershell

    - name: Install conda dependencies
      run: |
        conda install -y -c conda-forge python=${{ matrix.python-version }} wxpython>=4.2.2
        conda info -a
        conda list

    - name: Install dependencies with pip
      run: |
        python -m pip install psutil pyYAML PyPubSub ruamel.yaml matplotlib
       
    - name: Test DEVSimPy on Windows Server
      run: |
        cd devsimpy
        python devsimpy.py ../examples/model0/model0.dsp 10
