### local lauch: act -j build

name: Test Installing DEVSimPy on Ubuntu (latest), using conda

on:
    push:
      branches:
        - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        python-version: ['3.10','3.11','3.12','3.13']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python with Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        conda-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        python-version: ${{ matrix.python-version }}

    - name: Install conda dependencies
      run: |
        conda install -y -c conda-forge python=${{ matrix.python-version }} numpy=>1.22 matplotlib=>3.6 wxpython=>4.2 pip
        conda info -a
        conda list

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir --prefer-binary \
            psutil \
            pyYAML \
            PyPubSub \
            ruamel.yaml \
            matplotlib \
            openai \
            ollama
    
    - name: Test DEVSimPy with xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run python devsimpy.py examples/model0/model0.dsp 10 start quit