### Test Installing DEVSimPy on Ubuntu (latest), using conda

### To use from DEVSimPy local repo: 
###   1. lauch Docker
###   2. open a powershell terminal
###   3. execute: act -j build-ubuntu
###   4. if act is not installed, execute: winget install nektos.act
###   5. restart the terminal

name: Ubuntu build

on:
    push:
      branches:
        - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # X Display is not supported on parallel jobs
      fail-fast: true # Stop all jobs if one fails
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python with Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: latest
        conda-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        python-version: ${{ matrix.python-version }}

    - name: Install conda dependencies
      run: |
        conda install -y -c conda-forge python=${{ matrix.python-version }} wxpython>=4.2.2
        conda info -a
        conda list

    - name: Install dependencies with pip
      run: |
        python -m pip install --no-cache-dir --prefer-binary \
            psutil \
            pyYAML \
            PyPubSub \
            ruamel.yaml \
            matplotlib
    
    - name: Test DEVSimPy with xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
        cd devsimpy
        
        ### Test of DEVSimPy (open, start simulation during 10 time step and close)
        xvfb-run python devsimpy.py ../examples/model0/model0.dsp 10 autostart autoclose
        
        ### Test of diag and sub frame
        # xvfb-run python CheckGUI.py --autoclose
        # xvfb-run python ConnectDialog.py --autoclose
        # xvfb-run python DetachedFrame.py --autoclose
        # xvfb-run python DiagramConstantsDialog.py --autoclose
        # xvfb-run python Editor.py --autoclose
        # xvfb-run python FindGUI.py --autoclose
        # xvfb-run python FTPGui.py --autoclose
        # xvfb-run python HtmlWindow.py --autoclose
        # xvfb-run python ImportLibrary.py --autoclose
        # xvfb-run python LabelGUI.py --autoclose
        # xvfb-run python PreferencesGUI.py --autoclose
        # xvfb-run python PriorityGUI.py --autoclose
        # xvfb-run python SimulationGUI.py --autoclose
        # xvfb-run python WizardGUI.py --autoclose
        # xvfb-run python wxPyMail.py --autoclose
        # xvfb-run python XMLModule.py --autoclose