name: CI

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # Plateformes prises en charge - https://github.com/actions/runner-images
        python: ["3.10"]  # Version de Python stable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install system dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            build-essential \
            libsdl2-dev \
            libnotify-dev \
            libgtk-3-dev \
            xvfb

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir --prefer-binary \
            wxpython \
            psutil \
            pyYAML \
            PyPubSub \
            ruamel.yaml \
            matplotlib \
            openai \
            ollama

      - name: Run DEVSimPy Test
        run: |
          xvfb-run python devsimpy.py examples/model0/model0.dsp 10 start quit

