name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev build-essential python3-dev libjpeg-dev libtiff5-dev \
            libsdl1.2-dev libgstreamer-plugins-base1.0-dev libnotify-dev \
            freeglut3-dev libsm-dev libgtk-3-dev libpng16-16 \
            libwebkit2gtk-4.0-dev libgstreamer-plugins-base1.0-dev at-spi2-core
          pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
          pip install PyPubSub pyyaml ruamel.yaml matplotlib
          python setup.py install


      - name: Run tests
        run: |
          xvfb-run --auto-servernum python devsimpy.py examples/model0/model0.dsp 10 start quit
