name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # OS différents
        python: ["3.10"]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}  # Use a stable Python version
          architecture: x64

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            build-essential \
            libsdl2-dev \
            libnotify-dev \
            libgtk-3-dev \
            xvfb

      - name: Upgrade pip, setuptools, and wheel
        run: |
          pip install --upgrade pip setuptools wheel

      - name: Install Python dependencies
        run: |
            pip install --no-cache-dir --prefer-binary \
            wxPython \
            psutil \
            pyYAML \
            PyPubSub \
            ruamel.yaml \
            matplotlib \
            openai \
            ollama

      - name: Run DEVSimPy Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          xvfb-run python devsimpy.py examples/model0/model0.dsp 10 start quit