name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Plateformes prises en charge
        python: ["3.10"]  # Version de Python stable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            build-essential \
            libsdl2-dev \
            libnotify-dev \
            libgtk-3-dev \
            xvfb

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install \
            sdl2 \
            gtk+3 \
            wxpython \
            libnotify

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python }}-

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir --prefer-binary \
            wxPython \
            psutil \
            pyYAML \
            PyPubSub \
            ruamel.yaml \
            matplotlib \
            openai \
            ollama

      - name: Run DEVSimPy Test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          xvfb-run python devsimpy.py examples/model0/model0.dsp 10 start quit

      - name: Run DEVSimPy Test (Windows & macOS)
        if: matrix.os != 'ubuntu-latest'
        run: |
          python devsimpy.py examples/model0/model0.dsp 10 start quit
