name: Code Quality Check

on:  
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Run Flake8 and mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ajuste selon ton projet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy

      - name: Run Flake8
        run: flake8 .

      - name: Run mypy
        run: mypy .
